export const UPDATE_DATA = "UPDATE_DATA"
export const DELETE_DATA = "DELETE_DATA"
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'